namespace: "cyberark"
name: "pas"
version: "1.0.23"
readme: README.md
authors:
    - CyberArk Business Development (@cyberark-bizdev)
    - Edward Nunez (@enunez-cyberark)
    - Joe Garcia (@infamousjoeg)
description: "This is a Collection of the CyberArk Ansible Security Automation toolkit."
license: "MIT"
tags:
  - cyberark
  - access
  - security
  - account
  - epv
  - vault
  - identity
  - credential
  - secret
  - privileged
repository: "https://github.com/cyberark/ansible-security-automation-collection"
issues: https://github.com/cyberark/ansible-security-automation-collection/issues
